### PR TITLE
Remove the type class

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR removes the type class from `esqueleto` and simplifies all relevant types.

### CODE REVIEW

**Comment by FintanH** [comment]
Fantastic :heart:

**Comment by parsonsmatt** [comment]
@bitemyapp This is a big breaking change. Think we should lodge this in a 3.0 release or 2.8?

**Comment by bitemyapp** [comment]
@parsonsmatt Based on http://hackage.haskell.org/package/esqueleto, I'd say this is a 3.0.

**Comment by parsonsmatt** [comment]
@AKurilin I know y'all use this library a lot. Would this change harm your code base? I'm going to check with Lumi's codebase as well.

For some additional motivation for this change, I'm working on some complicated SQL logic. Somehow, the type is getting fixed to `Esqueleto Ratio SqlQuery SqlBackend`, and it's giving *all kinds* of totally useless errors. I know this is a simple type error. If the type were concrete, then I'd get an immediate pointer to where `SqlExpr` is getting confused with `Ratio`.

**Comment by eborden** [comment]
@parsonsmatt This is a breaking change for us (Freckle). Though it is a breaking change I'd welcome.

**Comment by cdparks** [comment]
I think there are only two places we'd need to update. All of our other helpers use concrete `SqlQuery` and `SqlExpr`.

**Comment by parsonsmatt** [comment]
@eborden @cdparks Is it just a mechanical translation from `Esqueleto e q b => e x -> q (e y)` to `SqlExpr x -> SqlQuery (SqlExpr y)`, or is there some functionality that would be lost with this?

**Comment by cdparks** [comment]
Yeah, that's exactly the change we'd have to make. We wouldn't lose any functionality, and the upgrade path is like a one-liner.

**Comment by andrewthad** [comment]
I use a little bit of esqueleto in about a dozen different projects. I've never seen any value in having the typeclass since there's only one possible instance of it. I would be happy to see it go away.

**Comment by eborden** [comment]
@parsonsmatt FYI, @cdparks has already fixed this in our codebase. All uses were unnecessary. The transition will now be painless.

**Comment by parsonsmatt** [comment]
Thanks @eborden @cdparks :)

**Pull request merged**
