### PR TITLE
Allow persistent 2.6 and base 4.9

### LINKED ISSUE #7: base version constraint needs to be bumped
Right now it's set at < 4.9, but the current version is `base-4.9.0.0/installed-4.9`. Is this restriction really needed still?

### LINKED ISSUE #8: Persistent 2.6 compatibility
Title. Fair warning, I don't care about Esqueleto and Persistent having matchy-matchy versioning.

### PR DESCRIPTION
**Pull request by mrkkrp**
Close #7, close #8.

### CODE REVIEW

**Comment by mrkkrp** [comment]
@bitemyapp, So that's about it. I also improved travis script, so it uses newest stable stack version instead of that ancient one (which failed to work with GHC 8.0 `stack.yaml` for some reason), plus minor code cleanup.

**Comment by bitemyapp** [comment]
This is great, thank you. I'll see about cutting a release based on this.

**Comment by ilovezfs** [comment]
@bitemyapp have you gained upload/commit access to Hackage for the package yet?

**Comment by bitemyapp** [comment]
@ilovezfs Yeah 2.5.0 of http://hackage.haskell.org/package/esqueleto was me.

**Comment by ilovezfs** [comment]
Neat! Looking forward to the release with this PR included. Thanks for taking over this package.

**Pull request merged**
