### PR TITLE
Fix Postgres syntax for NOWAIT

### PR DESCRIPTION
**Pull request by ttuegel**
Before submitting your PR, check that you've:

- [ ] Bumped the version number.
- [ ] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html).
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock.
- [ ] Ran `stylish-haskell` and otherwise adhered to the [style guide](https://github.com/bitemyapp/esqueleto/blob/master/style-guide.yaml).

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR.
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts).

### CODE REVIEW

**Review by parsonsmatt — COMMENTED** [review]
Has this always been broken? Or is this a new postgres thing?

Please update the changelog and cabal file with a patch bump. Thanks!

**Comment by ttuegel** [comment]
> Has this always been broken? Or is this a new postgres thing?

As far as I know, this has always been broken. `NOWAIT` has been the syntax since at least PostgreSQL 11.

**Comment by parsonsmatt** [comment]
Indeed - this test fails:

```haskell
testPostgresqlLocking :: SpecDb
testPostgresqlLocking = do
    describe "noWait" $ do
        itDb "doesn't crash" $ do
            select $ do
                t <- Experimental.from $ table @Person
                EP.forUpdateOf t EP.noWait
                pure t

            asserting noExceptions

    describe "Monoid instance" $ do
```

Could you add that test in to `test/PostgreSQL/Test.hs` and update changelog/cabal with patch? Thanks!

**Review by parsonsmatt — APPROVED** [review]
Thanks so much!

**Pull request merged**
