### PR TITLE
Alias CTEs upon initialising

### LINKED ISSUE #372: Joining on a CTE multiple times creates name clashes
Only tested on version `3.5.10.1` on MySQL.

When you include a CTE in a join, that CTE is not given a fresh alias. This means that including that CTE twice (or more times) in a join chain, both instances of the CTE are given the same name, which is invalid SQL.

A small example:

```haskell
share [mkPersist sqlSettings] [persistLowerCase|
  A
    k Int
    v Int
    Primary k
  
  B
    k Int
    v Int
    Primary k
|]

q :: SqlQuery (SqlExpr (Value Int), SqlExpr (Value Int))
q = do
  bCte <- with $ do
    b <- from $ table @B
    return b
  
  a :& b1 :& b2 <- from $ table @A
    `innerJoin` bCte
    `on` (\(a :& b) -> a.k ==. b.k)
    `innerJoin` bCte
    `on` (\(a :& _ :& b2) -> a.k ==. b2.k)
  return (a.k, a.v +. b1.v +. b2.v)
```

This is the SQL code that gets generated:
```sql
WITH `cte` AS 
  SELECT `b`.`k` AS `v_k`, `b`.`v` AS `v_v`
  FROM `b`
)

SELECT `a`.`k`,  ((`a`.`v` + `cte`.`v_v`) + `cte`.`v_v`)
FROM `a`
INNER JOIN `cte`
  ON `a`.`k` = `cte`.`v_k`
INNER JOIN `cte`
  ON `a`.`k` = `cte`.`v_k`;
```

As you can see, both the first and the second join are refered to as `cte`. Ideally, Esqueleto would produce something like this
```sql
WITH `cte` AS 
  SELECT `b`.`k` AS `v_k`, `b`.`v` AS `v_v`
  FROM `b`
)

SELECT `a`.`k`,  ((`a`.`v` + `cte_1`.`v_v`) + `cte_2`.`v_v`)
FROM `a`
INNER JOIN `cte` AS `cte_1`
  ON `a`.`k` = `cte_1`.`v_k`
INNER JOIN `cte` AS `cte_2
  ON `a`.`k` = `cte_2`.`v_k`;
```

### PR DESCRIPTION
**Pull request by RikvanToor**
Hello. :)

This PR fixes #372 by adding a fresh alias whenever a common table expression is used within a query.

As described in the issue, previously this Haskell code
```haskell
share [mkPersist sqlSettings] [persistLowerCase|
  A
    k Int
    v Int
    Primary k
  
  B
    k Int
    v Int
    Primary k
|]

q :: SqlQuery (SqlExpr (Value Int), SqlExpr (Value Int))
q = do
  bCte <- with $ do
    b <- from $ table @B
    return b
  
  a :& b1 :& b2 <- from $ table @A
    `innerJoin` bCte
    `on` (\(a :& b) -> a.k ==. b.k)
    `innerJoin` bCte
    `on` (\(a :& _ :& b2) -> a.k ==. b2.k)
  return (a.k, a.v +. b1.v +. b2.v)
```

would generated this SQL query
```sql
WITH `cte` AS (
  SELECT `b`.`k` AS `v_k`, `b`.`v` AS `v_v`
  FROM `b`
)

SELECT `a`.`k`,  ((`a`.`v` + `cte`.`v_v`) + `cte`.`v_v`)
FROM `a`
INNER JOIN `cte`
  ON `a`.`k` = `cte`.`v_k`
INNER JOIN `cte`
  ON `a`.`k` = `cte`.`v_k`;
```

which is invalid. After this PR, it instead generates this SQL query:
```sql
WITH `cte` AS (
  SELECT `b`.`k` AS `v_k`, `b`.`v` AS `v_v`
  FROM `b`
)

SELECT `a`.`k`,  ((`a`.`v` + `cte2`.`v_v`) + `cte3`.`v_v`)
FROM `a`
INNER JOIN `cte` AS `cte2`
  ON `a`.`k` = `cte2`.`v_k`
INNER JOIN `cte` AS `cte3`
  ON `a`.`k` = `cte3`.`v_k`
```

I'm not 100% satisfied with this, as the aliasing is only required when a single CTE is used multiple times in a single query, but my PR applies the aliasing at all times. I was not sure how to check for such a situation from within the context of the `with` function, so perhaps this PR can serve as a conversation about that. Thanks a lot!

---

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR.
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts).

### CODE REVIEW

**Comment by belevy** [comment]
please add a test that would fail to work without this fix. As far as aliasing only on duplicates, how do we handle it with regular table joins?

**Comment by jonathanmoregard** [comment]
> please add a test that would fail to work without this fix. As far as aliasing only on duplicates, how do we handle it with regular table joins?

See https://github.com/bitemyapp/esqueleto/issues/372.

I'm pretty sure I've run into the same issue in our production app :)

**Comment by parsonsmatt** [comment]
I'll incorporate the test and try to get this released today. Thanks!

**Comment by parsonsmatt** [comment]
Closing in favor of #410 - thanks for the great work!

**Comment by RikvanToor** [comment]
@parsonsmatt Thanks a lot! This has been in the back of my mind for a very long time, but I never got around to doing it.

**Pull request closed without merging**
