### PR TITLE
Also export ValidOnClauseValue

### PR DESCRIPTION
**Pull request by Vlix**
This is a constraint on `on`, but not exported, so you have to go into the source to see what it does. Exporting makes this easier.

(I don't think any `ChangeLog` or version edits are necessary for this)

### CODE REVIEW

**Comment by parsonsmatt** [comment]
This exports a new term, which would be a minor change, and thus requires an entry in the changelog and a new version.

**Comment by parsonsmatt** [comment]
fixed the CI stuff in #233 , merge that in and try again?

**Comment by Vlix** [comment]
@parsonsmatt should be fine now? :+1:

**Comment by parsonsmatt** [comment]
thanks so much!

**Pull request merged**
